version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4850:4850
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
